// This file is autogenerated. Changes will be overwritten.
#include "SOYZ2DITOJ/moc_documentosui.cpp"
#include "SOYZ2DITOJ/moc_uaderpass.cpp"
#include "XJOF3KNGPY/moc_npcgenericoui.cpp"
#include "XJOF3KNGPY/moc_npcui.cpp"
#include "EWIEGA46WW/moc_gamescreen.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_pantallainicio.cpp"
